service: authorization-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: "eu-west-1"
  stage: dev
  profile: apyrkh_aws_practitioner
  environment:
    AUTH_USER: ${env:AUTH_USER}
    AUTH_PASSWORD: ${env:AUTH_PASSWORD}

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

resources:
  Outputs:
    BasicAuthorizerFunctionArn:
      # Normalized name <CamelCaseName>LambdaFunction
      # https://www.serverless.com/framework/docs/providers/aws/guide/resources/
      Value: !GetAtt BasicAuthorizerLambdaFunction.Arn
      Description: BasicAuthorizer function will be used for other stacks
      Export:
        Name: ${self:service}-${self:provider.stage}-BasicAuthorizerFunctionArn
